# Generated by Django 2.2.6 on 2019-10-31 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='relationship',
            name='first_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_first', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='second_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_second', to='people.Person'),
        ),
    ]
