# Generated by Django 4.0.1 on 2022-01-24 10:19

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', people.models.PersonManager()),
            ],
        ),
        migrations.AddField(
            model_name='relationshipstatus',
            name='confirmed_by',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'First'), (2, 'Second'), (3, 'Both')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=3),
        ),
    ]
