# Generated by Django 4.0.1 on 2022-04-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_person_username_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
