# Generated by Django 3.0b1 on 2019-11-10 12:56

from django.db import migrations, models
import people.utils


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20191031_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshipstatus',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.IntegerField(choices=[(1, 'Elementary school'), (2, 'High school'), (3, 'University'), (4, 'Seminar'), (5, 'Other')]),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(default=people.utils.random_token, max_length=128),
        ),
    ]
