# Generated by Django 3.0b1 on 2019-11-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20191110_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ('-date_started',)},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-birth_date',), 'verbose_name_plural': 'people'},
        ),
        migrations.AlterModelOptions(
            name='relationshipstatus',
            options={'get_latest_by': ('date_end', 'date_start'), 'ordering': ('-date_start',), 'verbose_name_plural': 'relationship statuses'},
        ),
        migrations.AddField(
            model_name='verificationtoken',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
