# Generated by Django 4.0.1 on 2022-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_contactemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactemail',
            name='sure_its_active',
            field=models.BooleanField(default=True),
        ),
    ]
