# Generated by Django 4.0.1 on 2022-04-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_contactemail_sure_its_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactemail',
            unique_together={('person', 'email')},
        ),
    ]
