# Generated by Django 4.0.1 on 2022-04-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_contactemail_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='apology_status',
            field=models.CharField(choices=[('unsent', 'Unsent'), ('sent', 'Sent'), ('read', 'Read')], default='unsent', max_length=128),
        ),
    ]
