# Generated by Django 4.0.1 on 2022-04-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.IntegerField(choices=[(1, 'Account activation'), (2, 'Password reset'), (3, 'Auth token')], default=1, verbose_name='type'),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('type', 'token')},
        ),
    ]
